# Start from the official Pytorch image with CUDA support
FROM pytorch/pytorch:2.7.1-cuda12.6-cudnn9-runtime


RUN apt-get update && \
    apt-get install -y git

# Install necessary Python packages for data handling and S3 access
# s3fs requires aiobotocore
RUN pip install --no-cache-dir \
    boto3 \
    s3fs \
    mlflow \
    aiobotocore

# Create an /app directory for our code
WORKDIR /app

#Load the training script
COPY airflow/dags/scripts/train.py .

#Copying data into the container in order to speed up testing time
COPY airflow/data/dataset/ ./dataset/

#Preload efficient net
RUN python -c "from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights; print('Downloading EfficientNet_B0 weights...'); _ = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT); print('Weights cached.')"

