# Start from the official Pytorch image with CUDA support
FROM pytorch/pytorch:2.7.1-cuda12.6-cudnn9-runtime

# Install necessary Python packages for data handling and S3 access
# s3fs requires aiobotocore
RUN pip install --no-cache-dir \
    boto3 \
    s3fs \
    mlflow \
    aiobotocore

# Create an /app directory for our code
WORKDIR /app

COPY airflow/dags/scripts/train.py .